version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    create_environment:
      - echo "Preparing environment..."
    install:
      - echo "Installing dependencies..."
    build:
      html:
        - echo "Building HTML..."
    post_build:
      - echo "Build complete!"       

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

