version: 2

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: ./docs/

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - echo "Successfully grabbed latest version of RoboFlock Documentation!"
    pre_system_dependencies:
      - echo "Installing dependencies..."
    post_system_dependencies:
      - echo "Successfully installed dependencies!"
    pre_create_environment:
      - echo "Preparing environment..."
      - pip install --upgrade pip
    pre_build:
      - echo "Building HTML document..."
    post_build:
      - echo "Build complete!"       

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

